# Interface language: "ru" or "en"
language: "ru"

# Logger level: debug | info | warn | error
log_level: "info"

hide_secrets_in_console: true

# How many logical processors to use for generation.
# MUST be less than the number of available logical CPUs on the computer.
# 0 or no value â€” use all available ones.
cores: 8